# Generated by Django 6.1 on 2026-09-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSession',
            fields=[
                ('session_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=20)),
                ('red_flag_detected', models.BooleanField(default=False)),
                ('red_flag_data', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('complaint_duration', models.CharField(blank=True, max_length=100)),
                ('onset', models.TextField(blank=True)),
                ('progression', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('associated_symptoms', models.TextField(blank=True)),
                ('aggravating_factors', models.TextField(blank=True)),
                ('relieving_factors', models.TextField(blank=True)),
                ('character', models.TextField(blank=True)),
                ('radiation', models.TextField(blank=True)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('past_medical_history', models.TextField(blank=True)),
                ('past_surgical_history', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('drug_allergies', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('personal_history', models.TextField(blank=True)),
                ('review_of_systems', models.JSONField(blank=True, default=dict)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clinical.clinicalsession')),
            ],
        ),
        migrations.CreateModel(
            name='AYUSHHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prakriti', models.TextField(blank=True)),
                ('vikriti', models.TextField(blank=True)),
                ('sara', models.TextField(blank=True)),
                ('samhanana', models.TextField(blank=True)),
                ('pramana', models.TextField(blank=True)),
                ('satmya', models.TextField(blank=True)),
                ('sattva', models.TextField(blank=True)),
                ('ahara_shakti', models.TextField(blank=True)),
                ('vyayama_shakti', models.TextField(blank=True)),
                ('vaya', models.TextField(blank=True)),
                ('agni', models.TextField(blank=True)),
                ('koshtha', models.TextField(blank=True)),
                ('ahara_vihara', models.TextField(blank=True)),
                ('nidana', models.TextField(blank=True)),
                ('samprapti', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ayush_history', to='clinical.clinicalsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('ai_generated', models.BooleanField(default=True)),
                ('doctor_verified', models.BooleanField(default=False)),
                ('doctor_edited', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='clinical.clinicalsession')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('input_type', models.CharField(choices=[('VOICE', 'Voice'), ('TOUCH', 'Touch'), ('TEXT', 'Text')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clinical.clinicalsession')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinical.clinicalsession')),
            ],
        ),
    ]
