# Generated by Django 6.1 on 2026-09-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsession',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('HI', 'Hindi')], max_length=15),
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('ALLOPATHIC', 'Allopathic'), ('AYUSH', 'AYUSH')], max_length=20),
        ),
    ]
