spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}
  address: 0.0.0.0

django:
  api:
    key: ${DJANGO_API_KEY:the-key}

jwt:
  secret: ${JWT_SECRET:w9K8v3Qx7mL2pR6tY4nV0cA5sD1fG8hJk3Zx6Wq9B2M=}

gemini:
  api:
    key: ${GEMINI_API_KEY:the-key}