spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${PORT:10000}
  address: 0.0.0.0

django:
  api:
    key: ${DJANGO_API_KEY:the-key}

jwt:
  secret: ${JWT_SECRET:the-key}

gemini:
  api:
    key: ${GEMINI_API_KEY:the-key}